import { test, expect } from '@playwright/test';

test('sample: room setup, manual placement, collision, lock, undo, save and restore', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:5173');
  await expect(page.getByRole('heading', { name: 'A-01', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '서버실 설정', exact: true }).click();
  await page.getByRole('textbox', { name: '서버실 이름' }).fill('QA 서버실');
  await page.getByRole('spinbutton', { name: '가로 (mm)', exact: true }).fill('13200');
  await page.getByRole('button', { name: '설정 적용' }).click();
  await expect(page.locator('#r3-room-summary')).toContainText('13.2');
  await page.locator('[data-action=place]').first().click();
  await expect(page.getByRole('heading', { name: 'A-05', exact: true })).toBeVisible();
  await page.getByRole('spinbutton', { name: 'X (mm)', exact: true }).fill('2400');
  await page.getByRole('spinbutton', { name: 'Z (mm)', exact: true }).fill('3000');
  await page.getByRole('spinbutton', { name: 'Z (mm)', exact: true }).press('Tab');
  await expect(page.locator('#r3-invalid')).toContainText('겹칩니다');
  await expect(page.getByRole('button', { name: '배치 저장', exact: true })).toBeDisabled();
  await page.getByRole('spinbutton', { name: 'X (mm)', exact: true }).fill('7200');
  await page.getByRole('spinbutton', { name: 'X (mm)', exact: true }).press('Tab');
  await page.getByRole('combobox', { name: '방향', exact: true }).selectOption('90');
  await expect(page.locator('#r3-invalid')).toBeHidden();
  await page.getByRole('checkbox', { name: '잠금', exact: true }).check();
  await expect(page.getByRole('spinbutton', { name: 'X (mm)', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: '배치 해제', exact: true })).toBeDisabled();
  await page.getByRole('checkbox', { name: '잠금', exact: true }).uncheck();
  await page.getByRole('button', { name: '배치 해제', exact: true }).click();
  await expect(page.locator('#r3-scene-stats')).toContainText('4 / 8');
  await page.getByRole('button', { name: '↶ 되돌리기', exact: true }).click();
  await expect(page.locator('#r3-scene-stats')).toContainText('5 / 8');
  await page.getByRole('button', { name: '배치 저장', exact: true }).click();
  await expect(page.locator('#r3-save-state')).toContainText('v1');
  await page.reload();
  await expect(page.locator('#r3-room-summary')).toContainText('QA 서버실');
  await expect(page.locator('#r3-scene-stats')).toContainText('5 / 8');
  await page.getByRole('checkbox', { name: '배치된 랙 포함', exact: true }).check();
  await page.locator('[data-rack="105"] [data-action=select]').first().click();
  await expect(page.getByRole('spinbutton', { name: 'X (mm)', exact: true })).toHaveValue('7200');
  await expect(page.getByRole('combobox', { name: '방향', exact: true })).toHaveValue('90');
  expect(errors).toEqual([]);
});

test('sample: top view pointer drag persists the rack movement', async ({ page }) => {
  await page.goto('http://127.0.0.1:5173');
  await expect(page.getByRole('heading', { name: 'A-01', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '평면 배치', exact: true }).click();
  // The CSS2D label tracks the actual projected centre of the rack; drag just below it.
  const label = page.locator('.r3-label.active');
  const bounds = await label.boundingBox();
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2 + 12);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width / 2 - 45, bounds.y + bounds.height / 2 + 12, { steps: 10 });
  await page.mouse.up();
  await expect(page.getByRole('spinbutton', { name: 'X (mm)', exact: true })).not.toHaveValue('2400');
  await expect(page.locator('#r3-invalid')).toBeHidden();
  await page.getByRole('button', { name: '배치 저장', exact: true }).click();
  const x = await page.getByRole('spinbutton', { name: 'X (mm)', exact: true }).inputValue();
  await page.reload();
  await expect(page.getByRole('spinbutton', { name: 'X (mm)', exact: true })).toHaveValue(x);
});

test('NetBox: save through UI, verify database API, front/rear images and appearance', async ({ page }) => {
  const errors = [], failedImages = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.url().includes('/media/') && r.status() >= 400) failedImages.push(r.url()); });
  await page.goto('http://127.0.0.1:18080/plugins/room-3d/');
  await page.getByRole('textbox', { name: 'Username', exact: true }).fill('room3d-demo');
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('room3d-local-demo');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('combobox', { name: 'Location 선택', exact: true }).selectOption({ label: 'Room3D Demo IDC / 서버실 A' });
  await expect(page.getByRole('heading', { name: 'A-01', exact: true })).toBeVisible();
  await expect(page.locator('#r3-location')).toBeVisible();
  await expect(page.locator('#room3d .ts-wrapper')).toHaveCount(0);
  const previousX = await page.getByRole('spinbutton', { name: 'X (mm)', exact: true }).inputValue();
  const changedX = previousX === '1800' ? '2400' : '1800';
  await page.getByRole('spinbutton', { name: 'X (mm)', exact: true }).fill(changedX);
  await page.getByRole('spinbutton', { name: 'X (mm)', exact: true }).press('Tab');
  const saveResponse = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().includes('/data/locations/'));
  await page.getByRole('button', { name: '배치 저장', exact: true }).click();
  expect((await saveResponse).status()).toBe(200);
  await expect(page.locator('#r3-notice')).toContainText('저장했습니다');
  await page.getByRole('button', { name: '다시 불러오기', exact: true }).click();
  await expect(page.getByRole('spinbutton', { name: 'X (mm)', exact: true })).toHaveValue(changedX);
  await page.getByRole('button', { name: '전면 보기', exact: true }).click();
  await page.getByRole('button', { name: 'room3d-srv-01-01 Demo 2U with images U2', exact: true }).click();
  await expect(page.locator('.r3-face-preview img')).toHaveCount(2);
  await expect.poll(() => page.locator('.r3-face-preview img').evaluateAll(images => images.every(i => i.complete && i.naturalWidth > 0))).toBe(true);
  await page.screenshot({ path: 'artifacts/netbox-front.png', fullPage: true });
  await page.getByRole('button', { name: '후면 보기', exact: true }).click();
  await page.screenshot({ path: 'artifacts/netbox-rear.png', fullPage: true });
  await page.getByRole('button', { name: 'room3d-srv-01-03 Demo 2U color U10', exact: true }).click();
  const colorInput = page.getByLabel('이미지가 없는 면의 색상', { exact: true });
  const nextColor = (await colorInput.inputValue()) === '#f97316' ? '#a855f7' : '#f97316';
  await colorInput.fill(nextColor);
  await page.getByLabel('이미지가 없는 면의 색상', { exact: true }).press('Tab');
  await page.getByRole('button', { name: '배치 저장', exact: true }).click();
  await expect(page.locator('#r3-save-state')).not.toContainText('변경');
  await page.getByRole('button', { name: '다시 불러오기', exact: true }).click();
  await page.getByRole('button', { name: 'room3d-srv-01-03 Demo 2U color U10', exact: true }).click();
  await expect(page.getByLabel('이미지가 없는 면의 색상', { exact: true })).toHaveValue(nextColor);
  await page.getByRole('button', { name: '3D 보기', exact: true }).click();
  await page.screenshot({ path: 'artifacts/netbox-verified.png', fullPage: true });
  expect(errors).toEqual([]); expect(failedImages).toEqual([]);
});
